### YamlMime:Role 
title: Developer [開發人員] 
metadata: 
  title: Developer [開發人員] 
  description: 開發人員設計，組建，測試和維護解決方案。開發人員透過與解決方案架構師和客戶合作，來實作應用程式和服務。
uid: role.developer 
summary: | 
  開發人員設計，組建，測試和維護解決方案。開發人員透過與解決方案架構師和客戶合作，來實作應用程式和服務。 
subTitle: 開發人員設計、組建、測試和維護雲解決方案。
certificationPaths: 
- title: Azure Developer
  linkedInKeywords: Azure Developer
  uid: certification-path.developer 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-developer
    levels:
    - intermediate 
- title: Dynamics 365 Finance and Operations Apps Developer
  linkedInKeywords: Dynamics 365 Finance and Operations Apps Developer
  uid: certification-path.d365-finance-and-operations-apps-developer-associate
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-finance-and-operations-apps-developer-associate
    levels:
    - intermediate 
- title: Microsoft 365 Developer
  linkedInKeywords: Microsoft 365 Developer
  uid: certification-path.m365-developer-associate
  prerequisites: 
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.m365-developer-associate
    levels:
    - intermediate 
- title: Power Platform Developer
  linkedInKeywords: Power Platform Developer
  uid: certification-path.power-platform-developer-associate
  prerequisites: 
  - uid: certification.power-platform-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.power-platform-developer-associate
    levels:
    - intermediate
certifications:
- uid: certification.azure-developer
  requiredExams:
  - uid: exam.az-204
- uid: certification.d365-finance-and-operations-apps-developer-associate
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-500
- uid: certification.m365-developer-associate
  requiredExams:
  - uid: exam.ms-600
- uid: certification.power-platform-developer-associate
  requiredExams:
  - uid: exam.pl-400
- uid: certification.azure-iot-developer-specialty
  requiredExams:
  - uid: exam.az-220
resources:
- title: Microsoft 訓練和認證指南
  description: 透過一份簡潔的訓練和認證指南探索所有認證。
  href: https://aka.ms/TrainingCertDeck
- title: 訓練和認證海報
  description: 透過此訓練和認證海報選取您的成功路徑。
  href: https://aka.ms/traincertposter
- title: 支援認證
  href: ../help.md
  description: 透過 Microsoft Certification 支援論壇取得幫助。論壇主持人將在週一至週五的一個工作日內做出回應。
